title: "Vue.js自作 (タイトル未定)"
topics: ["Vue", "仮想DOM", "コンパイラ", "リアクティブシステム", "自作"]
published: false
chapters:
  - 001_about
  - 002_what_is_vue
  - 003_vue_core_components
  - 004_setup_project
  - 005_create_app_api
  - 006_simple_h_function
  - 007_minimum_reactive
  - 008_minimum_virtual_dom
  - 009_minimum_component
  - 010_minimum_template_compiler
  - 011_more_complex_parser
  - 012_template_binding
  - 013_minimum_sfc
  - 014_break
  - 100_bvd_patch_keyed_children
  - 110_bvd_bit_flags
  - 120_bvd_scheduler
  - 130_bvd_patch_other_attrs
  - 200_brs_ref_api
  - 210_brs_computed_watch
  - 212_brs_reactive_proxy_handlers
  - 220_brs_effect_scope
  - 230_brs_other_apis
  - 300_bcs_lifecycle_hooks
  - 310_bcs_provide_inject
  - 315_bcs_component_proxy_setup_context
